# Generated by Django 4.2.1 on 2023-05-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graficas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha',
        ),
        migrations.AddField(
            model_name='producto',
            name='ano',
            field=models.IntegerField(default=2023),
        ),
        migrations.AddField(
            model_name='producto',
            name='mes',
            field=models.CharField(default='enero', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='moneda',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
